### PR TITLE
Yk rm old lowerings

### PR DESCRIPTION
**Pull request by vext01**
This is just removing stuff that I *obviously* won't need in the new TIR.

I also renamed MIR to TIR, since that strikes me as confusing.

There will be a related compiler change. Testing now.

### CODE REVIEW

**Comment by vext01** [comment]
Companion PR:
https://github.com/softdevteam/ykrustc/pull/21

**Comment by vext01** [comment]
This is a rustfmt thing. Odd because I did remember to run it this time.

**Comment by ltratt** [comment]
Please rustfmt and squash at the same time.

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
splat

**Pull request merged**
