### PR TITLE
Use FM for TIR tests.

### PR DESCRIPTION
**Pull request by vext01**
Now we can use our hard work on `fm` in `yk` :)

See commit messages for details.

### CODE REVIEW

**Comment by bjorn3** [comment]
Do you know about https://github.com/bytecodealliance/filecheck?

**Comment by vext01** [comment]
spotted a typo

**Comment by ltratt** [comment]
> Do you know about https://github.com/bytecodealliance/filecheck?

I did not! It looks interesting, but I think it's complementary rather than a replacement? We're aiming for a very simple text matcher, in a sense a small superset of the features that https://crates.io/crates/lang_tester has (principally adding name matching), so that we can (simplifying a bit) paste test output in, minimally alter it, and have it be a useful test. If we need something more flexible, `filecheck` does look very useful!

**Comment by ltratt** [comment]
Oops, I fat-fingered the "close" button -- sorry :/

**Comment by vext01** [comment]
OK to squash?

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
splat.

**Pull request merged**
