### PR TITLE
Make ykpack::Body's attributes private.

### PR DESCRIPTION
**Pull request by ltratt**
This was a bit more involved than I expected as ykrustc gets mutable references in more than one place.

See also https://github.com/softdevteam/ykrustc/pull/181.

### CODE REVIEW

**Comment by vext01** [comment]
This seems ok to me. We need an override directive in the PR descr, right?

**Comment by ltratt** [comment]
There is one in the ykrustc side of this PR.

**Comment by vext01** [comment]
Ah yes. Sorry.

**Pull request merged**
