### PR TITLE
Fix ykview trace viewer

### PR DESCRIPTION
**Pull request by bjorn3**

### CODE REVIEW

**Comment by vext01** [comment]
I wonder why CI didn't catch these?

**Comment by bjorn3** [comment]
ykview doesn't have any tests.

**Comment by vext01** [comment]
Ah, I assumed these were compilation errors.

I was just trying to use ykview, and I'm not certain it's being built by xtask.

**Comment by bjorn3** [comment]
It is built by xtask when using `cargo xtask test`.

**Pull request merged**
