### PR TITLE
Rename IPlace to IRPlace.

### PR DESCRIPTION
**Pull request by ptersilie**
Companion PR: #172

### CODE REVIEW

**Comment by ptersilie** [comment]
Needs a rebase now. Ok to do so?

**Comment by ltratt** [comment]
Please go ahead.

**Comment by ptersilie** [comment]
Rebased. Don't know why this one didn't get through, but #260 did. So let's just try again.

**Comment by ltratt** [comment]
Isn't https://github.com/softdevteam/ykrustc/pull/172 the one that needs to be fixed and merged first?

**Pull request merged**
