### PR TITLE
Unify the buildbot testing of the 3 packages

### PR DESCRIPTION
**Pull request by ltratt**
Surprisingly this worked first time:

  http://bencher12.soft-dev.org:8010/#/builders/2/builds/123

I've checked the log and it really is executing all of the tests we want. I should have bought a lottery ticket instead...

### CODE REVIEW

**Comment by vext01** [comment]
> I should have bought a lottery ticket instead...

Wanna go halfs next time?

This LGTM, but we need to add a bors config file (derive from the existing one in yktrace?) and then enable bors on this repo. I can help with this, but let's get the existing BB config into a repo before we break it ;)

**Comment by vext01** [comment]
> This LGTM, but we need to add a bors config file (derive from the existing one in yktrace?) and then enable bors on this repo. I can help with this, but let's get the existing BB config into a repo before we break it ;)

So the buildbot config is in git now, to move this forward:
 * copy in a bors config (move the one from the `yktrace` subdir up, or here's one https://github.com/softdevteam/ykrustc/blob/master/bors.toml)
 * Enable bors on the repo (use https://github.com/apps/bors)
 * Adjust `.buldbot.sh` to use a ykrustc snapshot? (maybe as a separate PR, as the PR to make the snapshot isn't merged yet).

**Comment by ltratt** [comment]
Can I suggest you do those steps? You know each of them, and I don't, and so we'd probably do best to use your expertise. We can do that in this PR, and then ask someone else to review it, or we can merge this PR, and then you can open one doing those steps.

**Comment by vext01** [comment]
I can do yeah.

**Comment by ltratt** [comment]
Thanks! Would you prefer doing it in this PR or a fresh one?

**Comment by vext01** [comment]
Let's do the first two points in the above bullet list in this PR. But let me clear my PR backlog first.

**Comment by ltratt** [comment]
OK.

**Comment by vext01** [comment]
bors ping

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
bors try-

The snapshot PR was merged, so we might aswell do that here too.

**Comment by vext01** [comment]
Last commit is a stab at using the snapshot tarballs for testing, but it wont work until this is merged:
https://github.com/softdevteam/ykrustc/pull/15

**Comment by vext01** [comment]
bors try-

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
Hrm, it appears cargo is still not installed...

**Comment by ltratt** [comment]
I think the problem is `export PATH=ykrustc-stage2/bin:/usr/bin:/bin` -- shouldn't the first entry be `/opt/...`?

**Comment by vext01** [comment]
The path is correct, there's only a tarball in /opt and we've already untarred it.

I've done post-mortem on the buildbot worker and build no cargo binary anywhere, so my guess is that the extended tools are a dependency of `cargo install`.

Trying using that instead...

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
We should have rustdoc in the snapshot now.

bors try

**Comment by vext01** [comment]
The error was:
```
error: couldn't load codegen backend "/home/buildbot-worker3/bencher12-worker3/buildbot-build-script/build/ykrustc-stage2-latest/stage2/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so": "librustc_codegen_ssa-f1ca8b381804e885.so: cannot open shared object file: No such file or directory"
```

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
This is now ready for review, but since we've both pushed, we'd need a third-party. Assigning @jacob-hughes

**Comment by jacob-hughes** [comment]
LGTM. Looks like you had some fun getting buildbot to work :) Feel free to squash.

**Comment by vext01** [comment]
splat

**Comment by vext01** [comment]
[don't forget to not use the green button! I can disable that after this merge]

**Pull request merged**
