### PR TITLE
Reinstate ignored array slice test.

### PR DESCRIPTION
**Pull request by vext01**
Companion PR ~~coming~~ https://github.com/softdevteam/ykrustc/pull/159

This test was checking that a) MIR `Len` rvalues are correctly lowered
to SIR, and that b) the JIT correctly accesses the length in the second
part of the slice's fat pointer (as part of an array indexing operation).

I've managed to fix the test and simplify it in doing so.

I also found a bug in `copy_memory`, where loading the first operand to
memmove(3) overwrote the place we'd load the second operand from.

### CODE REVIEW

**Comment by ltratt** [comment]
Please squash.

**Comment by bjorn3** [comment]
There is only a single commit at the moment...

**Comment by vext01** [comment]
Rebased.

**Comment by vext01** [comment]
This is good to go now.

**Pull request merged**
