### PR TITLE
Address refactoring of yk in ykrustc's libcore

### PR DESCRIPTION
**Pull request by ptersilie**
This PR addresses the changes in https://github.com/softdevteam/ykrustc/pull/76.

Requires cycle breaker commits in order to be merged.

### CODE REVIEW

**Comment by vext01** [comment]
This is fine.

**Comment by vext01** [comment]
This is ready for bors now, right?

**Comment by ptersilie** [comment]
Yes it is!

**Comment by vext01** [comment]
```diff
-use core::yk::{SirLoc, swt};
+use core::yk::{swt, SirLoc};
```

**Comment by ptersilie** [comment]
Fixed the `cargo fmt` error. Please `r+` again.

**Pull request merged**
