### PR TITLE
Less allocations

### PR DESCRIPTION
**Pull request by bjorn3**
This may not matter a lot, but still it should be a small perf win.

Based on #191

### CODE REVIEW

**Comment by ltratt** [comment]
Are you able to rebase this against master so that it doesn't pull in commits from #191? If not, please feel free to leave as-is.

**Comment by ltratt** [comment]
This isn't part of the code base I'm super familiar with. I guess my main question to @vext01 (or @ptersilie? but I think this is mostly Edd's work) is whether we want to leak this memory for the lifetime of a process or not. If SIR can never be "unloaded" (in some sense of that term) I guess it doesn't matter, though memory leaks do make me mildly queasy, in the sense that they at least make leak checking tools more noisy to use.

**Comment by vext01** [comment]
Do the string slices have to be `'static` lifetime? Could they be `'a` so that we don't have to leak in that one case?

**Comment by vext01** [comment]
>  If SIR can never be "unloaded"

At the moment it's considered eternal.

>  though memory leaks do make me mildly queasy

Same here. I'd rather not, but then again it's only in `ykview` which is just a debugging aid for dumping SIR from a binary. It's not part of the JIT proper.

**Comment by ltratt** [comment]
Yeah, I just realised what's going on -- I forgot that this is referring to something already in the binary! I'm fine with this, because the `ykview` situation is reasonable.

**Comment by bjorn3** [comment]
> Do the string slices have to be `'static` lifetime? Could they be `'a` so that we don't have to leak in that one case?

I tried but ran into lifetime trouble. As a next step I want to replace the `SirTrace` trait with a struct which may make it easier to do this.

**Comment by bjorn3** [comment]
Rebased

**Pull request merged**
