### PR TITLE
Types in yk.

### PR DESCRIPTION
**Pull request by vext01**
Companion to https://github.com/softdevteam/ykrustc/pull/111

### CODE REVIEW

**Comment by ptersilie** [comment]
Looks good. Needs a rebase though.

**Comment by vext01** [comment]
Rebased, but added two commits for fixes. Ok to squash in?

**Comment by ptersilie** [comment]
Yes, please squash.

**Comment by vext01** [comment]
splat.

**Comment by vext01** [comment]
CI is primed.

**Pull request merged**
