### PR TITLE
Add basic projections.

### PR DESCRIPTION
**Pull request by ptersilie**
Companion PR to https://github.com/softdevteam/ykrustc/pull/110.

Adding @ltratt in face of @vext01's absence.

### CODE REVIEW

**Comment by ptersilie** [comment]
Started a manual build of ykrustc on CI. Once that's finished this will be ready for merging. I'll leave a note when that happens.

**Comment by ltratt** [comment]
I'm happy to merge this. If you want to try one of these things, you can just do `bors try` on the PR. I do that quite often!

**Comment by ptersilie** [comment]
bors try

**Comment by ptersilie** [comment]
This is ready for merging now.

**Pull request merged**
