### PR TITLE
Rearrange terminators and define human-readable forms for them.

### PR DESCRIPTION
**Pull request by vext01**
I did consider decomposing the terminators into a regular statements and a smaller set of TIR terminators, however, I have a gut feeling that we will need stuff like the unwinding details explicit. In light of that, I've almost mirrored the MIR terminators.

A corresponding compiler change is coming.

### CODE REVIEW

**Comment by vext01** [comment]
Sorry, hold of reviewing this one. I forgot to add the `SwitchInt` "values" field to our terminators.

**Comment by ltratt** [comment]
OK.

**Comment by vext01** [comment]
I've been bitten yet again by https://github.com/softdevteam/yk/issues/4, so I'm going to also address this.

**Comment by vext01** [comment]
The endgame of those last three commits is the addition of the `values` field to the `SwitchInt` terminator.

 * I killed the `Drop` implementation to understand why ykrustc was crashing (fixes #4 ). It turned out to be that I was trying to serialise a u128 again. 
 * Since I then needed serialisable 128-bit ints in two places (and I'm sure more will come), I made re-usable types for them.
 * Finally implemented `values` for `SwitchInt` using one of those new types.

Commit messages have more detail.

More effort than expected!

This is ready for review, but please don't merge just yet. I'm still building ykrustc against this.

**Comment by ltratt** [comment]
When you're happy, please squash.

**Comment by vext01** [comment]
Spotted a couple of bugs by viewing the CFG:
image

**Comment by vext01** [comment]
That last push shows how this'd look using a parameterised type instead of two concrete types.

Unexpectedly, I prefer with the two concrete types. And you?

**Comment by ltratt** [comment]
Fine with me. Squash?

**Comment by vext01** [comment]
> Fine with me

So you prefer the latter? In which case we disagree on which is nicest.

**Comment by ltratt** [comment]
Ah, I see what you mean Let me reconsider this tomorrow.

**Comment by ltratt** [comment]
Looking at this again, I'm pretty much neutral, so go with what you prefer.

**Comment by vext01** [comment]
OK, reverted the last commit then. Just building / testing...

**Comment by vext01** [comment]
I think this is now ready to be squashed.

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
splat.

**Comment by vext01** [comment]
I'm going to try git absorb properly for this one, bear with me.

**Comment by ltratt** [comment]
Hang on, we shouldn't be squashing yet should we?

**Comment by vext01** [comment]
I was just experimenting. The last commit is what we will need to squash.

Shall I go ahead.

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
splat.

**Pull request merged**
