### PR TITLE
Store size and alignment alongside each type.

### PR DESCRIPTION
**Pull request by ptersilie**
We already did something similar for structs, tuples, etc. Now we are
doing the same for all types and thus no longer need to specify these
values manually.

### CODE REVIEW

**Comment by vext01** [comment]
I'm a big fan of this change!

There's a register allocation test with a FIXME that mentions tuple layouts (just merged today). Would you mind adding a "tiny tuple" case to it?

**Comment by ptersilie** [comment]
Sure. Let me have a look.

**Comment by ptersilie** [comment]
> Would you mind adding a "tiny tuple" case to it?

As discussed offline, you were referring to `enum`s, which we haven't lowered yet, so there's nothing to do here for now.

**Pull request merged**
