### PR TITLE
Add the ability to get the trace inputs local index.

### PR DESCRIPTION
**Pull request by vext01**
Accompanies https://github.com/softdevteam/ykrustc/pull/108

### CODE REVIEW

**Comment by ptersilie** [comment]
Looks good!

**Comment by ptersilie** [comment]
CI priming seems to be finished. Let's try!

bors r+

**Comment by vext01** [comment]
No, it's crashing for a reason I don't understand.

**Comment by ptersilie** [comment]
Oh!

bors r-

**Comment by vext01** [comment]
```
error: failed to get `ykpack` as a dependency of package `rustc_codegen_ssa v0.0.0 (/home/buildbot-worker2/worker2/ykrustc-buildbot-build-script-hwt/build/src/librustc_codegen_ssa)`
Caused by:
  failed to load source for dependency `ykpack`
Caused by:
  Unable to update https://github.com/vext01/yk?branch=yk-trace-inputs#2687ea58
```

**Comment by ptersilie** [comment]
Yes, saw that just now. Maybe Github was briefly unreachable? Maybe just try again. I don't really have a better idea at the moment.

**Comment by vext01** [comment]
I've tried a couple of times.

**Comment by vext01** [comment]
Ok sorted. Try now.

**Comment by vext01** [comment]
Can I squash?

**Comment by ptersilie** [comment]
Please squash.

**Comment by vext01** [comment]
splat.

**Pull request merged**
