### PR TITLE
Add `num_locals` to `Body`.

### LINKED ISSUE #106: Add num_args field to ykpack::Body
This is necessary for a verifier. It also helps you know what local_decls are arguments by only looking at a single SIR body.

### PR DESCRIPTION
**Pull request by vext01**
Fixes #106.

Companion PR ~~coming~~: https://github.com/softdevteam/ykrustc/pull/124

### CODE REVIEW

**Review by bjorn3 — APPROVED** [review]

**Comment by vext01** [comment]
OK to squash?

**Comment by bjorn3** [comment]
Yes

**Comment by vext01** [comment]
splat. Just waiting for the companion to prime now.

**Pull request merged**
