### PR TITLE
Restructure tests dir.

### LINKED ISSUE #221: Layout of tests/src/yktrace.rs
The structure of `tests/src/yktrace.rs` seems a bit odd, at least at first glance. There are top-level `#[test]`s, then a `mod tir` and more `#[test]`s inside it. I wondered if this is necessary, or whether we can simplify this?

### PR DESCRIPTION
**Pull request by vext01**
How do you folks feel about this? We don't have to merge it.

This commit:
 - Groups tests by what they test, rather than where they originally
   came from.
 - Adds module docstrings.

Before:
```
./lib.rs
./tracing
./yksg.rs
./test_helpers.c
./helpers.rs
./guardfailure.rs
./ykcompile.rs
./yktrace.rs
```

After:
```
./lib.rs
./tir.rs
./test_helpers.c
./helpers.rs
./tracing.rs
./codegen
./codegen/mod.rs
./codegen/reg_alloc.rs
./stopgap
./stopgap/mod.rs
./stopgap/interp.rs
./stopgap/guard_fail.rs
```

fixes #221

### CODE REVIEW

**Comment by ltratt** [comment]
I'm not sure I understand where the extra files in "after" have come from. Am I missing something obvious?

**Comment by vext01** [comment]
It's where I've split larger files containing different kinds of tests into smaller groupings.

This was actually inspired by a comment you made somewhere (i can't find it now). You were questioning why one of the test files contained two kinds of tests.

**Comment by ltratt** [comment]
https://github.com/softdevteam/yk/issues/221 maybe?

**Comment by vext01** [comment]
For example, `yktrace` contained low-level tracing tests and some TIR tests. The TIR tests were moved to `tir.rs`.

**Comment by vext01** [comment]
> #221 maybe?

That's the one. Look, I'm even saying I plan to do this very PR :P

**Comment by ltratt** [comment]
Got it! Even if this isn't perfect, it's an improvement at the very least. @ptersilie are you OK with this?

**Comment by ptersilie** [comment]
Yep, this works for me.

**Pull request merged**
