### PR TITLE
Deal with CI changes.

### PR DESCRIPTION
**Pull request by vext01**

### CODE REVIEW

**Comment by bjorn3** [comment]
It is still waiting for ykrustc-buildbot-build-script-hwt it seems.

**Comment by bjorn3** [comment]
The bors dashboard reports:

```
{{:badmatch,
   {:error, :push, 422,
    "{\"message\":\"Required status check \\\"buildbot/ykrustc-buildbot-build-script-hwt\\\" is expected.\",\"documentation_url\":\"https://docs.github.com/articles/about-protected-branches\"}"}},
  [
    {BorsNG.Worker.Batcher, :complete_batch, 3,
     [file: 'lib/worker/batcher.ex', line: 712]},
    {BorsNG.Worker.Batcher, :maybe_complete_batch, 1,
     [file: 'lib/worker/batcher.ex', line: 658]},
    {BorsNG.Worker.Batcher, :handle_cast, 2,
     [file: 'lib/worker/batcher.ex', line: 94]},
    {:gen_server, :try_dispatch, 4,
     [file: 'gen_server.erl', line: 637]},
    {:gen_server, :handle_msg, 6,
     [file: 'gen_server.erl', line: 711]},
    {:proc_lib, :init_p_do_apply, 3,
     [file: 'proc_lib.erl', line: 249]}
  ]}
```

**Comment by vext01** [comment]
GH was misconfigured. @ltratt please retry.

**Comment by vext01** [comment]
@ptersilie in short, we renamed `STD_TRACER_MODE` and also the builder name for things for Yorick.

Laurie has already OKd this, just needs a kick.

**Comment by ltratt** [comment]
@ptersilie has beaten me to it!

**Pull request merged**
