### PR TITLE
Remove rustfmt config and try to be more robust against rustfmt not building

### PR DESCRIPTION
**Pull request by ltratt**

### CODE REVIEW

**Comment by ltratt** [comment]
bors try

**Comment by vext01** [comment]
LGTM

**Comment by vext01** [comment]
I'll wait for your try...

**Comment by vext01** [comment]
You need to unset the tracing RUSTFLAGS before using the nightly toolchain.

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
Shouldn't I squash?

**Comment by vext01** [comment]
oops.

**Pull request merged**
