### PR TITLE
None of the tests currently run but make at least one semi-runnable.

### PR DESCRIPTION
**Pull request by ltratt**
The test this commit fiddles with now compiles (even if it's uncommented!) but fails because ykrt currently throws a `todo!()`. However, it still seems useful to slightly unbreak this, so that when ykrt does work, we can quickly get at
least one test up and running.

### CODE REVIEW

**Comment by vext01** [comment]
If I see it correctly, you've made a test compile, but left it commented?

Would it be better to uncomment it and mark in `#[ignore]` so that it is at least "compile tested"?

**Comment by ltratt** [comment]
Good idea! Fixed in https://github.com/softdevteam/yk/pull/328/commits/a6f948addfe7b108105c9a94bbffab77876d28aa.

**Comment by vext01** [comment]
Please squash.

**Comment by ltratt** [comment]
It seems that rustfmt has changed a lot (?!) so the `cargo fmt` is a bit brutal https://github.com/softdevteam/yk/pull/328/commits/1df27a33876fd01b948f03e7289d7f8e8dcac51c.

**Comment by vext01** [comment]
please squash.

**Comment by ltratt** [comment]
Squashed.

**Pull request merged**
