### PR TITLE
Reduce api surface of ykcompile

### PR DESCRIPTION
**Pull request by bjorn3**

### CODE REVIEW

**Comment by ltratt** [comment]
This looks fine to me. OK with you @vext01?

**Comment by vext01** [comment]
I don't object, but I'd also like to double check with @ptersilie who wrote the initial ykcompile interface.

@bjorn3, out of interest, is this just for good programming practice sake, or does reducing the export surface help with something you are working on?

**Comment by ptersilie** [comment]
Looks fine to me, though I'm also curious if there's a greater reason for these changes.

**Comment by bjorn3** [comment]
This is related to my plan of trying to compile the internals of Yorick with a regular rustc that has optimizations enabled and doesn't have any overhead from tracing independent of the kind of tracing. This requires an `extern "C"` interface between the internals and the ykrt crate. I don't know yet how it will work out, but I think the reduced api surface is a good thing independent of this plan.

**Comment by vext01** [comment]
> This is related to my plan of trying to compile the internals of Yorick with a regular rustc that has optimizations enabled.

Can't argue with that :)

I guess you are going to compile the JIT stuff externally instead of using the regular dependency management. Sounds doable.

Anyway, please resolve conflicts.

**Comment by bjorn3** [comment]
> I guess you are going to compile the JIT stuff externally instead of using the regular dependency management.

I think I will try to use `build.rs` to compile it with a regular rustc.

> Anyway, please resolve conflicts.

Done

**Comment by bjorn3** [comment]
Had to run rustfmt.

**Comment by vext01** [comment]
Please squash.

**Comment by bjorn3** [comment]
Splat

**Pull request merged**
