### PR TITLE
Ignore trace_tail test for the hardware tracer

### PR DESCRIPTION
**Pull request by ptersilie**
See issue #38

### CODE REVIEW

**Comment by vext01** [comment]
Something weird is going on here.

The commit in question passed according to buildbot. There's a green tick next to the commit.

**Comment by vext01** [comment]
image

**Comment by ltratt** [comment]
Given the previous attempt timed out, maybe that's the problem this time too?

**Comment by ltratt** [comment]
It seems it did take 8 hours to run yesterday...

**Comment by vext01** [comment]
Buildbot sent the "it worked" message for the commit in question (for both hwt and swt builds) at 11:10am this morning (about 4 minutes after my r+):
```
2019-11-27 11:10:42+0000 [HTTP11ClientProtocol (TLSMemoryBIOProtocol),client] Updated status with "success" for softdevteam/yk at e1bbc5a419c41c6c33035e8446f434611a3e9401, context "buildbot/ykrustc-buildbot-build
-script-hwt", issue None.
2019-11-27 11:10:59+0000 [HTTP11ClientProtocol (TLSMemoryBIOProtocol),client] Updated status with "success" for softdevteam/yk at e1bbc5a419c41c6c33035e8446f434611a3e9401, context "buildbot/ykrustc-buildbot-build-script-swt", issue None
```

Before that, on the timed out build, buildbot sent the github notification at about 14:14:
```
2019-11-27 11:10:42+0000 [HTTP11ClientProtocol (TLSMemoryBIOProtocol),client] Updated status with "success" for softdevteam/yk at e1bbc5a419c41c6c33035e8446f434611a3e9401, context "buildbot/ykrustc-buildbot-build
-script-hwt", issue None.
2019-11-26 14:13:57+0000 [HTTP11ClientProtocol (TLSMemoryBIOProtocol),client] Updated status with "success" for softdevteam/yk at 1760ebb04eabf78fefed55f6856033fa76267415, context "buildbot/ykrustc-buildbot-build
-script-hwt", issue None.
```

Again, a few mintues after the `r+`.

As I write this I think I see the problem: `bors.toml`:
```
status = [
  "buildbot/buildbot-build-script"
]
```

Should be:

```
status = [
  "buildbot/ykrustc-buildbot-build-script-hwt",
  "buildbot/ykrustc-buildbot-build-script-swt",
]
```

Bors is waiting for a notification which buildbot will never send!

@ptersilie can you push a fix in a new commit?

**Comment by ptersilie** [comment]
Let's try this!

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
OK, that works. Can you expand the commit message for the fix and I will r+ this.

You just need to say that in the transition to two builds (hw+sw), we forgot to update the status messages bors is expecting to see.

**Comment by ptersilie** [comment]
You don't want me to squash it?

**Comment by ptersilie** [comment]
Like so?

**Comment by vext01** [comment]
sorry to nitpick, but
> that are send to Github.

*sent*

> You don't want me to squash it?

We don't want to squash as the change is unrelated.

**Comment by ptersilie** [comment]
Already fixed. I noticed it immediately and hoped I would be fast enough before you even look at it. Guess I wasn't.

**Comment by ptersilie** [comment]
Ah wait. I did have `sent` initially and then changed it to `send`. I'm an idiot!

**Comment by ptersilie** [comment]
Okay, it's back to what it was initially.

**Comment by vext01** [comment]
bors crashed!

bors r-

**Comment by vext01** [comment]
Once more for luck

bors r+

**Comment by vext01** [comment]
@ptersilie it's still expecting the old status message.

We may have to re-raise the PR?

image

**Comment by ptersilie** [comment]
Okay, I will close this one and then open a new one.

**Pull request closed without merging**
