### PR TITLE
 Ignore trace_tail test for the hardware tracer

### PR DESCRIPTION
**Pull request by ptersilie**
This is the same PR as #39, which we had to re-raise due to changes in bors. See #39 for more details.

### CODE REVIEW

**Comment by ptersilie** [comment]
bors try

**Comment by ltratt** [comment]
If you need to squash first, please do so.

**Comment by ptersilie** [comment]
Actually, nevermind, I've already done that in the old version of this PR. This whole PR has been a bit messy so I was momentarily confused. You can `r+` it again.

**Comment by ptersilie** [comment]
Okay, this is still borked. I don't think we'll be able to fix this without @vext01. Given `try` works, we may just have to force merge this.

**Comment by ltratt** [comment]
> Required status check \\\"buildbot/buildbot-build-script

I'm wondering if bors hasn't been updated on b13 and/or not restarted?

**Comment by ptersilie** [comment]
Unfortunately, I don't know enough about bors to comment on that.

**Comment by ltratt** [comment]
I've tried restarting it, just in case.

bors r+

**Comment by ltratt** [comment]
@ptersilie Can you try force pushing an update to your last commit (e.g. just update the time) because that last r+ didn't seem to actually run anything (I think it cached the previous cancel).

**Comment by ltratt** [comment]
Scrap that!

**Comment by ltratt** [comment]
I might have found the problem.

bors r+

**Comment by ltratt** [comment]
We hadn't updated the status checks in GitHub -> Settings -> Branches. I've done that now and the problem seems to be solved.

**Comment by ptersilie** [comment]
Ah, excellent!

**Comment by vext01** [comment]
Thanks for sorting this Laurie!

**Pull request merged**
