### PR TITLE
[3/3] Move trace input to yktrace

### PR DESCRIPTION
**Pull request by bjorn3**
Depends on https://github.com/softdevteam/ykrustc/pull/121

### CODE REVIEW

**Comment by vext01** [comment]
This looks good to me.

Please squash.

**Comment by bjorn3** [comment]
Should I keep the second and third commit separate?

**Comment by vext01** [comment]
It's up to you.

(We used to try and ensure every commit compiled so that we could bisect, but in reality it's very hard due to the dependency on very specific versions of ykrustc)

**Comment by bjorn3** [comment]
All commits should work independent of each other and except for ab7e4eb independent of the ykrustc changes.

**Comment by vext01** [comment]
Well, if you can make it so that every commit works, then that's great, but don't obsess about it if it's too annoying :)

**Comment by bjorn3** [comment]
I try to keep the history clean for myself. I often have changes applied locally that shouldn't be committed (like making it compile without ykrustc in a hackish in this case), so creating independent commits for independent changes is not much more effort.

**Comment by vext01** [comment]
So no squashing required, or?

**Comment by bjorn3** [comment]
I squashed everything that makes sense for this PR. It will likely need a cycle breaker though.

**Comment by vext01** [comment]
Yes.

In your ykrustc PR, edit the top level `Cargo.toml` and override the ykpack dependency to this repo and branch, then do a `bors try`.

Our CI caches the last successful build of ykrustc and uses it for subsequent builds of this repo, so we can then merge this.

Then once that's done, we revert the dep patching in `ykrustc` and update the lock file, before merging that.

 It's not pretty, but we've not found a better way...

**Comment by bjorn3** [comment]
Wait, does the ykrustc test suite run the tests of this repo? If not then the cycle breaker should not be necessary.

**Comment by vext01** [comment]
Currently the ykrustc CI doesn't run the yk tests.

**Comment by vext01** [comment]
> This branch is out-of-date with the base branch

Can you rebase and check it doesn't break anything?

**Comment by bjorn3** [comment]
Rebased and tested.

**Comment by vext01** [comment]
You probably didn't see that because it's in hardware tracer specific code.

**Comment by bjorn3** [comment]
I accidentally edited the hwtracer checkout in ~/.cargo/git/checkouts`. I dropped 9cd766d, so it should now work.

**Pull request merged**
